# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308bc85c3865b4852ab5e0147fc0d00c4ca80f2a6a41907751e894bf5d0e2caf43297199dca1a7a842d9743d4e70a9350119c0c1e07de297c4d424f27f72d058

test:
  secret_key_base: 6b90c5e682bd3d1f5cbf0212b29a35f05f10478ab375c6b105a11d85c2bb42c388473bdfaf73901863366e19d19d64d286874d715e113b67c2b65099481cd0e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
